/*
 * This RPC client stub was autogenerated by idlc. DO NOT EDIT!
 * Generated from Filesystem.idl for interface Filesystem at 2021-06-24T01:30:24-0500
 *
 * You may use these generated stubs directly as the RPC interface, or you can subclass it to
 * override the behavior of the function calls, or to perform some preprocessing to the data as
 * needed before sending it.
 *
 * See the full RPC documentation for more details.
 */
#include "Client_Filesystem.hpp"
#include "Filesystem.capnp.h"

#include <algorithm>
#include <cstdlib>
#include <cstdio>
#include <cstring>

#include <capnp/message.h>
#include <capnp/serialize.h>

#include <rpc/rt/RpcIoStream.hpp>

using namespace rpc;

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
using Client = FilesystemClient;

/**
 * Creates a new client instance, with the given IO stream.
 */
Client::FilesystemClient(const std::shared_ptr<IoStream> &stream) : io(stream) {
}

/**
 * Shuts down the RPC client, releasing any allocated resources.
 */
Client::~FilesystemClient() {
    if(this->txBuf) {
        free(this->txBuf);
    }
}

/// Assemble a message with the given type.
uint32_t Client::_sendRequest(const uint64_t type, const std::span<std::byte> &payload) {
    const size_t len = sizeof(MessageHeader) + payload.size();
    this->_ensureTxBuf(len);

    const auto tag = __atomic_add_fetch(&this->nextTag, 1, __ATOMIC_RELAXED);
    auto hdr = reinterpret_cast<MessageHeader *>(this->txBuf);
    memset(hdr, 0, sizeof(*hdr));
    hdr->type = type;
    hdr->flags = MessageHeader::Flags::Request;
    hdr->tag = tag;

    memcpy(hdr->payload, payload.data(), payload.size());

    const std::span<std::byte> txBufSpan(reinterpret_cast<std::byte *>(this->txBuf), len);
    if(!this->io->sendRequest(txBufSpan)) {
        this->_HandleError(true, "Failed to send RPC request");
        return 0;
    }

    return tag;
}

// Allocates an aligned transmit buffer of the given size
void Client::_ensureTxBuf(const size_t len) {
    if(len > this->txBufSize) {
        if(this->txBuf) {
            free(this->txBuf);
        }
        int err = posix_memalign(&this->txBuf, 16, len);
        if(err) {
            return this->_HandleError(true, "Failed to allocate RPC send buffer");
        }
        this->txBufSize = len;
    }
}

/**
 * Handles an error that occurred on the client connection. Implementations may override this
 * method if they want to use exceptions, for example.
 *
 * @param fatal If set, the error precludes further operation on this RPC connection
 * @param what Descriptive string for the error
 */
void Client::_HandleError(const bool fatal, const std::string_view &what) {
    fprintf(stderr, "[RPC] %s: Encountered %s RPC error: %s\n", kServiceName.data(),
        fatal ? "fatal" : "recoverable", what.data());
    if(fatal) exit(-1);
}
/*
 * Autogenerated call method for 'OpenFile' (id $dccae6ca6448b367)
 * Have 2 parameter(s), 3 return(s); method is sync
 */
Client::OpenFileReturn Client::OpenFile(const std::string &path, uint32_t mode) {
    uint32_t sentTag;
    {
        capnp::MallocMessageBuilder requestBuilder;
        auto request = requestBuilder.initRoot<rpc::_proto::messages::OpenFileRequest>();
        request.setPath(path);
        request.setMode(mode);
        auto rw = capnp::messageToFlatArray(requestBuilder);
        auto rb = rw.asBytes();
        const std::span<std::byte> rs(reinterpret_cast<std::byte *>(rb.begin()), rb.size());
        sentTag = this->_sendRequest(rpc::_proto::messages::MESSAGE_ID_OPEN_FILE, rs);
    }
    {
        std::span<std::byte> buf;
        if(!this->io->receiveReply(buf)) this->_HandleError(false, "Failed to receive RPC reply");
        if(buf.size() < sizeof(MessageHeader)) this->_HandleError(false, "Received message too small");
        const auto hdr = reinterpret_cast<const MessageHeader *>(buf.data());
        if(hdr->tag != sentTag) this->_HandleError(false, "Invalid tag in reply RPC packet");
        else if(hdr->type != rpc::_proto::messages::MESSAGE_ID_OPEN_FILE) this->_HandleError(false, "Invalid type in reply RPC packet");
        const auto payload = buf.subspan(offsetof(MessageHeader, payload));

        kj::ArrayPtr<const capnp::word> message(reinterpret_cast<const capnp::word *>(payload.data()),
                payload.size() / sizeof(capnp::word));
        capnp::FlatArrayMessageReader reader(message);
        auto reply = reader.getRoot<rpc::_proto::messages::OpenFileResponse>();
        OpenFileReturn r;
        r.status =  reply.getStatus();
        r.handle =  reply.getHandle();
        r.fileSize =  reply.getFileSize();
        return r;

    }
}
/*
 * Autogenerated call method for 'SlowRead' (id $fb13530a05a3aaf2)
 * Have 3 parameter(s), 2 return(s); method is sync
 */
Client::SlowReadReturn Client::SlowRead(uint64_t handle, uint64_t offset, uint16_t numBytes) {
    uint32_t sentTag;
    {
        capnp::MallocMessageBuilder requestBuilder;
        auto request = requestBuilder.initRoot<rpc::_proto::messages::SlowReadRequest>();
        request.setHandle(handle);
        request.setOffset(offset);
        request.setNumBytes(numBytes);
        auto rw = capnp::messageToFlatArray(requestBuilder);
        auto rb = rw.asBytes();
        const std::span<std::byte> rs(reinterpret_cast<std::byte *>(rb.begin()), rb.size());
        sentTag = this->_sendRequest(rpc::_proto::messages::MESSAGE_ID_SLOW_READ, rs);
    }
    {
        std::span<std::byte> buf;
        if(!this->io->receiveReply(buf)) this->_HandleError(false, "Failed to receive RPC reply");
        if(buf.size() < sizeof(MessageHeader)) this->_HandleError(false, "Received message too small");
        const auto hdr = reinterpret_cast<const MessageHeader *>(buf.data());
        if(hdr->tag != sentTag) this->_HandleError(false, "Invalid tag in reply RPC packet");
        else if(hdr->type != rpc::_proto::messages::MESSAGE_ID_SLOW_READ) this->_HandleError(false, "Invalid type in reply RPC packet");
        const auto payload = buf.subspan(offsetof(MessageHeader, payload));

        kj::ArrayPtr<const capnp::word> message(reinterpret_cast<const capnp::word *>(payload.data()),
                payload.size() / sizeof(capnp::word));
        capnp::FlatArrayMessageReader reader(message);
        auto reply = reader.getRoot<rpc::_proto::messages::SlowReadResponse>();
        SlowReadReturn r;
        r.status =  reply.getStatus();
        const auto retBlob = reply.getData();
        r.data = std::vector<std::byte>(reinterpret_cast<const std::byte *>(retBlob.begin()),reinterpret_cast<const std::byte *>(retBlob.end()));
        return r;

    }
}
/*
 * Autogenerated call method for 'CloseFile' (id $be7b08fc61ccb369)
 * Have 1 parameter(s), 1 return(s); method is sync
 */
int32_t Client::CloseFile(uint64_t handle) {
    uint32_t sentTag;
    {
        capnp::MallocMessageBuilder requestBuilder;
        auto request = requestBuilder.initRoot<rpc::_proto::messages::CloseFileRequest>();
        request.setHandle(handle);
        auto rw = capnp::messageToFlatArray(requestBuilder);
        auto rb = rw.asBytes();
        const std::span<std::byte> rs(reinterpret_cast<std::byte *>(rb.begin()), rb.size());
        sentTag = this->_sendRequest(rpc::_proto::messages::MESSAGE_ID_CLOSE_FILE, rs);
    }
    {
        std::span<std::byte> buf;
        if(!this->io->receiveReply(buf)) this->_HandleError(false, "Failed to receive RPC reply");
        if(buf.size() < sizeof(MessageHeader)) this->_HandleError(false, "Received message too small");
        const auto hdr = reinterpret_cast<const MessageHeader *>(buf.data());
        if(hdr->tag != sentTag) this->_HandleError(false, "Invalid tag in reply RPC packet");
        else if(hdr->type != rpc::_proto::messages::MESSAGE_ID_CLOSE_FILE) this->_HandleError(false, "Invalid type in reply RPC packet");
        const auto payload = buf.subspan(offsetof(MessageHeader, payload));

        kj::ArrayPtr<const capnp::word> message(reinterpret_cast<const capnp::word *>(payload.data()),
                payload.size() / sizeof(capnp::word));
        capnp::FlatArrayMessageReader reader(message);
        auto reply = reader.getRoot<rpc::_proto::messages::CloseFileResponse>();
        return reply.getStatus();
    }
}
#pragma clang diagnostic pop
