/*
 * This RPC server stub was autogenerated by idlc. DO NOT EDIT!
 * Generated from Filesystem.idl for interface Filesystem at 2021-06-24T01:30:24-0500
 *
 * You should subclass this implementation and define the required abstract methods to complete
 * implementing the interface. Note that there are several helper methods available to simplify
 * this task, or to retrieve more information about the caller.
 *
 * See the full RPC documentation for more details.
 */
#include "Server_Filesystem.hpp"
#include "Filesystem.capnp.h"

#include <algorithm>
#include <cstdlib>
#include <cstring>
#include <stdexcept>

#include <rpc/rt/RpcIoStream.hpp>

#include <capnp/message.h>
#include <capnp/serialize.h>

using namespace rpc;

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
using Server = FilesystemServer;

/**
 * Creates a new server instance, with the given IO stream.
 */
Server::FilesystemServer(const std::shared_ptr<IoStream> &stream) : io(stream) {
}

/**
 * Releases any allocated resources.
 */
Server::~FilesystemServer() {
    if(this->txBuf) {
        free(this->txBuf);
    }
}

/**
 * Continuously processes messages until processing fails to receive another message.
 */
bool Server::run(const bool block) {
    bool cont;
    do {
        cont = this->runOne(block);
    } while(cont);
    return cont;
}

/**
 * Reads a single message from the RPC connection and attempts to process it.
 *
 * @return Whether a message was able to be received and processed.
 */
bool Server::runOne(const bool block) {
    // try to receive message
    std::span<std::byte> buf;
    if(!this->io->receive(buf, block)) return false;

    // get the message header and its payload
    if(buf.size() < sizeof(MessageHeader)) {
        this->_HandleError(false, "Received message too small");
        return false;
    }
    const auto hdr = reinterpret_cast<const MessageHeader *>(buf.data());

    const auto payload = buf.subspan(offsetof(MessageHeader, payload));

    // then invoke the appropriate marshalling function
    switch(hdr->type) {
        case rpc::_proto::messages::MESSAGE_ID_OPEN_FILE:
            this->_marshallOpenFile(*hdr, payload);
            break;
        case rpc::_proto::messages::MESSAGE_ID_SLOW_READ:
            this->_marshallSlowRead(*hdr, payload);
            break;
        case rpc::_proto::messages::MESSAGE_ID_CLOSE_FILE:
            this->_marshallCloseFile(*hdr, payload);
            break;
    }
    return true;
}



// Helper method to build and send a reply message
void Server::_doSendReply(const MessageHeader &inHdr, const std::span<std::byte> &payload) {
    const size_t len = sizeof(MessageHeader) + payload.size();
    this->_ensureTxBuf(len);

    auto hdr = reinterpret_cast<MessageHeader *>(this->txBuf);
    memset(hdr, 0, sizeof(*hdr));
    hdr->type = inHdr.type;
    hdr->flags = MessageHeader::Flags::Response;
    hdr->tag = inHdr.tag;

    memcpy(hdr->payload, payload.data(), payload.size());

    const std::span<std::byte> txBufSpan(reinterpret_cast<std::byte *>(this->txBuf), len);
    if(!this->io->reply(txBufSpan)) {
        this->_HandleError(false, "Failed to send RPC reply");
    }
}

// Allocates an aligned transmit buffer of the given size
void Server::_ensureTxBuf(const size_t len) {
    if(len > this->txBufSize) {
        if(this->txBuf) {
            free(this->txBuf);
        }
        int err = posix_memalign(&this->txBuf, 16, len);
        if(err) {
            this->_HandleError(true, "Failed to allocate RPC send buffer");
        }
        this->txBufSize = len;
    }
}

/**
 * Handles an error that occurred on the server connection. Implementations may override this
 * method if they want to use exceptions, for example.
 *
 * @param fatal If set, the error precludes further operation on this RPC connection
 * @param what Descriptive string for the error
 */
void Server::_HandleError(const bool fatal, const std::string_view &what) {
    fprintf(stderr, "[RPC] %s: Encountered %s RPC error: %s\n", kServiceName.data(),
        fatal ? "fatal" : "recoverable", what.data());
    if(fatal) exit(-1);
}
/*
 * Autogenerated marshalling method for 'OpenFile' (id $dccae6ca6448b367)
 * Have 2 parameter(s), 3 return(s); method is sync
 */
void Server::_marshallOpenFile(const MessageHeader &hdr, const std::span<std::byte> &payload) {
    kj::ArrayPtr<const capnp::word> message(reinterpret_cast<const capnp::word *>(payload.data()),
            payload.size() / sizeof(capnp::word));
    capnp::FlatArrayMessageReader reader(message);
    auto request = reader.getRoot<rpc::_proto::messages::OpenFileRequest>();
    const std::string dec_path(request.getPath());
    const auto dec_mode = request.getMode();

    auto retVal = this->implOpenFile(dec_path, dec_mode);

    capnp::MallocMessageBuilder replyBuilder;
    auto reply = replyBuilder.initRoot<rpc::_proto::messages::OpenFileResponse>();
    reply.setStatus(retVal.status);
    reply.setHandle(retVal.handle);
    reply.setFileSize(retVal.fileSize);
    {
        auto rw = capnp::messageToFlatArray(replyBuilder);
        auto rb = rw.asBytes();
        const std::span<std::byte> rs(reinterpret_cast<std::byte *>(rb.begin()), rb.size());
        this->_doSendReply(hdr, rs);
    }
}
/*
 * Autogenerated marshalling method for 'SlowRead' (id $fb13530a05a3aaf2)
 * Have 3 parameter(s), 2 return(s); method is sync
 */
void Server::_marshallSlowRead(const MessageHeader &hdr, const std::span<std::byte> &payload) {
    kj::ArrayPtr<const capnp::word> message(reinterpret_cast<const capnp::word *>(payload.data()),
            payload.size() / sizeof(capnp::word));
    capnp::FlatArrayMessageReader reader(message);
    auto request = reader.getRoot<rpc::_proto::messages::SlowReadRequest>();
    const auto dec_handle = request.getHandle();
    const auto dec_offset = request.getOffset();
    const auto dec_numBytes = request.getNumBytes();

    auto retVal = this->implSlowRead(dec_handle, dec_offset, dec_numBytes);

    capnp::MallocMessageBuilder replyBuilder;
    auto reply = replyBuilder.initRoot<rpc::_proto::messages::SlowReadResponse>();
    reply.setStatus(retVal.status);
    capnp::Data::Reader blobReader_data(reinterpret_cast<const kj::byte *>(retVal.data.data()), retVal.data.size());
    reply.setData(blobReader_data);
    {
        auto rw = capnp::messageToFlatArray(replyBuilder);
        auto rb = rw.asBytes();
        const std::span<std::byte> rs(reinterpret_cast<std::byte *>(rb.begin()), rb.size());
        this->_doSendReply(hdr, rs);
    }
}
/*
 * Autogenerated marshalling method for 'CloseFile' (id $be7b08fc61ccb369)
 * Have 1 parameter(s), 1 return(s); method is sync
 */
void Server::_marshallCloseFile(const MessageHeader &hdr, const std::span<std::byte> &payload) {
    kj::ArrayPtr<const capnp::word> message(reinterpret_cast<const capnp::word *>(payload.data()),
            payload.size() / sizeof(capnp::word));
    capnp::FlatArrayMessageReader reader(message);
    auto request = reader.getRoot<rpc::_proto::messages::CloseFileRequest>();
    const auto dec_handle = request.getHandle();

    auto retVal = this->implCloseFile(dec_handle);

    capnp::MallocMessageBuilder replyBuilder;
    auto reply = replyBuilder.initRoot<rpc::_proto::messages::CloseFileResponse>();
    reply.setStatus(retVal);
    {
        auto rw = capnp::messageToFlatArray(replyBuilder);
        auto rb = rw.asBytes();
        const std::span<std::byte> rs(reinterpret_cast<std::byte *>(rb.begin()), rb.size());
        this->_doSendReply(hdr, rs);
    }
}
#pragma clang diagnostic pop
