###############################################################################
# Default init script
#
# Define the servers to execute on boot-up. This is just enough to allow us to
# discover devices, and read filesystems for additional drivers.
#
# SERVER: Specifies the name of a server to launch. They are lauched in the
#         order specified.
###############################################################################
SERVER dyldosrv
SERVER driverman --expert=pc_amd64
